CREATE TABLE `candidate_news` (
	`id` int AUTO_INCREMENT NOT NULL,
	`candidateId` int NOT NULL,
	`title` varchar(300) NOT NULL,
	`summary` text,
	`content` text,
	`sourceUrl` text,
	`sourceName` varchar(100),
	`imageUrl` text,
	`topic` varchar(100),
	`publishedAt` timestamp NOT NULL DEFAULT (now()),
	`searchedAt` timestamp NOT NULL DEFAULT (now()),
	`isAutoGenerated` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `candidate_news_id` PRIMARY KEY(`id`)
);
