/**
 * Auto-Update Service
 * Automatically searches for new candidates, policies, and news every 6 hours
 */

import * as db from "./db";
import * as geminiSearch from "./gemini-search";
import { InsertCandidate } from "../drizzle/schema";

interface AutoUpdateResult {
  timestamp: Date;
  newCandidatesAdded: number;
  newsUpdated: number;
  policiesUpdated: number;
  errors: string[];
  details: {
    candidates: Array<{ name: string; county: string; party: string }>;
    newsCount: Record<string, number>;
  };
}

/**
 * Search and add new candidates for a specific county and position
 */
export async function searchAndAddCandidates(
  county: string,
  positionType: keyof typeof geminiSearch.POSITION_TYPES
): Promise<{ added: number; candidates: Array<{ name: string; party: string }> }> {
  const searchResults = await geminiSearch.searchNewCandidates(county, positionType);
  const addedCandidates: Array<{ name: string; party: string }> = [];

  for (const result of searchResults) {
    try {
      // Check if candidate already exists
      const existing = await db.getCandidateByNameAndCounty(result.name, county);
      if (existing) {
        console.log(`[AutoUpdate] Candidate ${result.name} already exists in ${county}`);
        continue;
      }

      // Create new candidate
      const candidateData: InsertCandidate = {
        name: result.name,
        party: result.party,
        county: result.county,
        district: result.district,
        positionType: result.positionType,
        bio: result.summary,
        isActive: true,
      };

      await db.createCandidate(candidateData);
      addedCandidates.push({ name: result.name, party: result.party });
      console.log(`[AutoUpdate] Added new candidate: ${result.name} (${result.party}) - ${county}`);
    } catch (error) {
      console.error(`[AutoUpdate] Error adding candidate ${result.name}:`, error);
    }
  }

  return { added: addedCandidates.length, candidates: addedCandidates };
}

/**
 * Update news for all active candidates
 */
export async function updateAllCandidateNews(): Promise<{
  updated: number;
  details: Record<string, number>;
}> {
  const candidates = await db.getCandidates({ isActive: true, limit: 100 });
  const details: Record<string, number> = {};
  let totalUpdated = 0;

  for (const candidate of candidates) {
    try {
      const newsResults = await geminiSearch.searchCandidateNewsWithSources(
        candidate.name,
        candidate.county
      );

      let candidateNewsCount = 0;
      for (const newsItem of newsResults) {
        await db.upsertCandidateNewsByTopic({
          candidateId: candidate.id,
          title: newsItem.title,
          summary: newsItem.summary,
          sourceUrl: newsItem.sourceUrl,
          sourceName: newsItem.sourceName,
          topic: newsItem.topic,
          publishedAt: newsItem.publishedDate ? new Date(newsItem.publishedDate) : new Date(),
          isAutoGenerated: true,
        });
        candidateNewsCount++;
      }

      details[candidate.name] = candidateNewsCount;
      totalUpdated += candidateNewsCount;
    } catch (error) {
      console.error(`[AutoUpdate] Error updating news for ${candidate.name}:`, error);
      details[candidate.name] = 0;
    }
  }

  return { updated: totalUpdated, details };
}

/**
 * Update policies for all active candidates
 */
export async function updateAllCandidatePolicies(): Promise<{
  updated: number;
  details: Record<string, number>;
}> {
  const candidates = await db.getCandidates({ isActive: true, limit: 100 });
  const categories = await db.getIssueCategories();
  const categoryMap = new Map(categories.map((c) => [c.name, c.id]));
  const details: Record<string, number> = {};
  let totalUpdated = 0;

  for (const candidate of candidates) {
    try {
      const policyResults = await geminiSearch.searchCandidatePolicies(
        candidate.name,
        candidate.county,
        candidate.positionType as keyof typeof geminiSearch.POSITION_TYPES
      );

      let candidatePolicyCount = 0;
      for (const policy of policyResults) {
        const categoryId = categoryMap.get(policy.category);
        await db.createPolicy({
          candidateId: candidate.id,
          categoryId: categoryId || undefined,
          title: policy.title,
          content: policy.content,
          summary: policy.content.substring(0, 100),
          source: policy.sourceUrl,
        });
        candidatePolicyCount++;
      }

      details[candidate.name] = candidatePolicyCount;
      totalUpdated += candidatePolicyCount;
    } catch (error) {
      console.error(`[AutoUpdate] Error updating policies for ${candidate.name}:`, error);
      details[candidate.name] = 0;
    }
  }

  return { updated: totalUpdated, details };
}

/**
 * Run full auto-update cycle
 * This should be called every 6 hours via scheduled task
 */
export async function runFullAutoUpdate(options?: {
  counties?: string[];
  positionTypes?: Array<keyof typeof geminiSearch.POSITION_TYPES>;
  skipNews?: boolean;
  skipPolicies?: boolean;
}): Promise<AutoUpdateResult> {
  const startTime = new Date();
  const errors: string[] = [];
  const addedCandidates: Array<{ name: string; county: string; party: string }> = [];
  let newsUpdated = 0;
  let policiesUpdated = 0;
  const newsDetails: Record<string, number> = {};

  // Default to major cities for now
  const counties = options?.counties || [
    "台北市", "新北市", "桃園市", "台中市", "台南市", "高雄市",
  ];
  const positionTypes = options?.positionTypes || ["mayor", "councilor"];

  console.log(`[AutoUpdate] Starting full auto-update at ${startTime.toISOString()}`);
  console.log(`[AutoUpdate] Counties: ${counties.join(", ")}`);
  console.log(`[AutoUpdate] Position types: ${positionTypes.join(", ")}`);

  // 1. Search for new candidates
  for (const county of counties) {
    for (const positionType of positionTypes) {
      try {
        const result = await searchAndAddCandidates(
          county,
          positionType as keyof typeof geminiSearch.POSITION_TYPES
        );
        for (const c of result.candidates) {
          addedCandidates.push({ ...c, county });
        }
      } catch (error) {
        const msg = `Error searching candidates in ${county} ${positionType}: ${error}`;
        console.error(`[AutoUpdate] ${msg}`);
        errors.push(msg);
      }
    }
  }

  // 2. Update news for all candidates
  if (!options?.skipNews) {
    try {
      const newsResult = await updateAllCandidateNews();
      newsUpdated = newsResult.updated;
      Object.assign(newsDetails, newsResult.details);
    } catch (error) {
      const msg = `Error updating news: ${error}`;
      console.error(`[AutoUpdate] ${msg}`);
      errors.push(msg);
    }
  }

  // 3. Update policies for all candidates (optional, can be resource-intensive)
  if (!options?.skipPolicies) {
    try {
      const policyResult = await updateAllCandidatePolicies();
      policiesUpdated = policyResult.updated;
    } catch (error) {
      const msg = `Error updating policies: ${error}`;
      console.error(`[AutoUpdate] ${msg}`);
      errors.push(msg);
    }
  }

  const result: AutoUpdateResult = {
    timestamp: startTime,
    newCandidatesAdded: addedCandidates.length,
    newsUpdated,
    policiesUpdated,
    errors,
    details: {
      candidates: addedCandidates,
      newsCount: newsDetails,
    },
  };

  console.log(`[AutoUpdate] Completed at ${new Date().toISOString()}`);
  console.log(`[AutoUpdate] Results:`, JSON.stringify(result, null, 2));

  // Log to database
  await db.logAutoUpdate("full", result);

  return result;
}

/**
 * Quick update - only search for new candidates in specified county
 */
export async function quickCandidateSearch(
  county: string,
  positionType: keyof typeof geminiSearch.POSITION_TYPES = "councilor"
): Promise<{ added: number; candidates: Array<{ name: string; party: string }> }> {
  console.log(`[AutoUpdate] Quick search for ${county} ${positionType}`);
  return searchAndAddCandidates(county, positionType);
}
