import { describe, it, expect, afterEach } from "vitest";
import { getDb } from "./db";
import { candidateNews } from "../drizzle/schema";
import { eq, desc } from "drizzle-orm";

describe("Candidate News API", () => {
  const TEST_CANDIDATE_ID = 999;

  afterEach(async () => {
    // Clean up test data after each test
    const db = await getDb();
    if (db) {
      await db.delete(candidateNews).where(eq(candidateNews.candidateId, TEST_CANDIDATE_ID));
    }
  });

  describe("getByCandidateId", () => {
    it("should return empty array when no news exists", async () => {
      const db = await getDb();
      if (!db) {
        console.warn("Database not available, skipping test");
        return;
      }

      const result = await db
        .select()
        .from(candidateNews)
        .where(eq(candidateNews.candidateId, TEST_CANDIDATE_ID))
        .limit(10);
      
      expect(result).toEqual([]);
    });

    it("should return news ordered by publishedAt desc", async () => {
      const db = await getDb();
      if (!db) {
        console.warn("Database not available, skipping test");
        return;
      }

      // Insert test news with Date objects
      const now = new Date();
      const yesterday = new Date(now.getTime() - 86400000);
      
      await db.insert(candidateNews).values([
        {
          candidateId: TEST_CANDIDATE_ID,
          title: "Older News",
          summary: "Old summary",
          topic: "Test",
          publishedAt: yesterday,
        },
        {
          candidateId: TEST_CANDIDATE_ID,
          title: "Newer News",
          summary: "New summary",
          topic: "Test2",
          publishedAt: now,
        },
      ]);

      const result = await db
        .select()
        .from(candidateNews)
        .where(eq(candidateNews.candidateId, TEST_CANDIDATE_ID))
        .orderBy(desc(candidateNews.publishedAt));

      expect(result.length).toBe(2);
      expect(result[0].title).toBe("Newer News");
      expect(result[1].title).toBe("Older News");
    });
  });

  describe("news deduplication by topic", () => {
    it("should check for existing topics before adding", async () => {
      const db = await getDb();
      if (!db) {
        console.warn("Database not available, skipping test");
        return;
      }

      const now = new Date();
      
      // Insert first news
      await db.insert(candidateNews).values({
        candidateId: TEST_CANDIDATE_ID,
        title: "First News",
        summary: "Summary",
        topic: "DuplicateTopic",
        publishedAt: now,
      });

      // Check if topic exists
      const existing = await db
        .select()
        .from(candidateNews)
        .where(eq(candidateNews.candidateId, TEST_CANDIDATE_ID));
      
      const existingTopics = existing.map(n => n.topic);
      expect(existingTopics).toContain("DuplicateTopic");
    });
  });

  describe("news schema validation", () => {
    it("should store all required fields", async () => {
      const db = await getDb();
      if (!db) {
        console.warn("Database not available, skipping test");
        return;
      }

      const now = new Date();
      
      await db.insert(candidateNews).values({
        candidateId: TEST_CANDIDATE_ID,
        title: "Test Title",
        summary: "Test Summary",
        topic: "Test Topic",
        sourceName: "Test Source",
        sourceUrl: "https://example.com/news",
        publishedAt: now,
        isAutoGenerated: true,
      });

      const result = await db
        .select()
        .from(candidateNews)
        .where(eq(candidateNews.candidateId, TEST_CANDIDATE_ID));

      expect(result.length).toBe(1);
      expect(result[0].title).toBe("Test Title");
      expect(result[0].summary).toBe("Test Summary");
      expect(result[0].topic).toBe("Test Topic");
      expect(result[0].sourceName).toBe("Test Source");
      expect(result[0].sourceUrl).toBe("https://example.com/news");
      expect(result[0].isAutoGenerated).toBe(true);
    });
  });
});
