/**
 * Scheduler Service
 * Runs automated tasks every 6 hours to update candidate data
 * 
 * Tasks:
 * 1. Update candidate basic info and policies
 * 2. Search and add new news articles
 */

import * as db from "./db";
import { searchCandidateNewsWithSources, searchCandidatePolicies } from "./gemini-search";

// 6 hours in milliseconds
const UPDATE_INTERVAL = 6 * 60 * 60 * 1000;

// Track scheduler state
let schedulerInterval: NodeJS.Timeout | null = null;
let isRunning = false;
let lastRunTime: Date | null = null;
let lastRunResult: SchedulerResult | null = null;

export interface SchedulerResult {
  timestamp: Date;
  candidatesProcessed: number;
  newsAdded: number;
  policiesAdded: number;
  errors: string[];
  details: {
    candidates: Array<{
      id: number;
      name: string;
      newsCount: number;
      policiesCount: number;
    }>;
  };
}

/**
 * Process a single candidate - update news and policies
 */
async function processCandidate(candidate: {
  id: number;
  name: string;
  county: string;
  party: string | null;
  positionType: string;
}): Promise<{
  newsCount: number;
  policiesCount: number;
  errors: string[];
}> {
  const errors: string[] = [];
  let newsCount = 0;
  let policiesCount = 0;

  try {
    // 1. Search and add news
    console.log(`[Scheduler] Searching news for ${candidate.name}...`);
    const newsResults = await searchCandidateNewsWithSources(candidate.name, candidate.county);
    
    for (const news of newsResults) {
      try {
        // Check if news with same topic already exists
        const existingNews = await db.getCandidateNewsByTopic(candidate.id, news.title);
        if (!existingNews) {
          await db.createCandidateNews({
            candidateId: candidate.id,
            title: news.title,
            summary: news.summary,
            sourceUrl: news.sourceUrl || "",
            sourceName: news.sourceName,
            topic: news.title.substring(0, 50), // Use first 50 chars of title as topic
            publishedAt: new Date(),
            isAutoGenerated: true,
          });
          newsCount++;
        }
      } catch (err) {
        errors.push(`Failed to add news "${news.title}": ${err}`);
      }
    }

    // 2. Search and add policies (only if candidate has few policies)
    const existingPolicies = await db.getPoliciesByCandidateId(candidate.id);
    if (existingPolicies.length < 3) {
      console.log(`[Scheduler] Searching policies for ${candidate.name}...`);
      const policyResults = await searchCandidatePolicies(
        candidate.name, 
        candidate.county,
        candidate.positionType as "mayor" | "councilor" | "township_mayor" | "representative" | "village_chief"
      );
      
      for (const policy of policyResults) {
        try {
          // Check if policy with same title already exists
          const existingPolicy = existingPolicies.find((p: { title: string }) => 
            p.title.toLowerCase() === policy.title.toLowerCase()
          );
          if (!existingPolicy) {
            await db.createPolicy({
              candidateId: candidate.id,
              title: policy.title,
              summary: policy.content.substring(0, 200), // Use first 200 chars as summary
              content: policy.content,
              source: policy.sourceUrl || "AI 搜尋",
              isHighlight: false,
            });
            policiesCount++;
          }
        } catch (err) {
          errors.push(`Failed to add policy "${policy.title}": ${err}`);
        }
      }
    }
  } catch (err) {
    errors.push(`Failed to process candidate ${candidate.name}: ${err}`);
  }

  return { newsCount, policiesCount, errors };
}

/**
 * Run the full update cycle
 */
export async function runScheduledUpdate(): Promise<SchedulerResult> {
  if (isRunning) {
    console.log("[Scheduler] Update already in progress, skipping...");
    return {
      timestamp: new Date(),
      candidatesProcessed: 0,
      newsAdded: 0,
      policiesAdded: 0,
      errors: ["Update already in progress"],
      details: { candidates: [] },
    };
  }

  isRunning = true;
  const startTime = new Date();
  console.log(`[Scheduler] Starting scheduled update at ${startTime.toISOString()}`);

  const result: SchedulerResult = {
    timestamp: startTime,
    candidatesProcessed: 0,
    newsAdded: 0,
    policiesAdded: 0,
    errors: [],
    details: { candidates: [] },
  };

  try {
    // Get all active candidates
    const candidates = await db.getCandidates();
    console.log(`[Scheduler] Found ${candidates.length} candidates to process`);

    // Process candidates in batches to avoid rate limiting
    const BATCH_SIZE = 5;
    const BATCH_DELAY = 10000; // 10 seconds between batches

    for (let i = 0; i < candidates.length; i += BATCH_SIZE) {
      const batch = candidates.slice(i, i + BATCH_SIZE);
      
      for (const candidate of batch) {
        try {
          const { newsCount, policiesCount, errors } = await processCandidate({
            id: candidate.id,
            name: candidate.name,
            county: candidate.county,
            party: candidate.party,
            positionType: candidate.positionType,
          });

          result.candidatesProcessed++;
          result.newsAdded += newsCount;
          result.policiesAdded += policiesCount;
          result.errors.push(...errors);
          result.details.candidates.push({
            id: candidate.id,
            name: candidate.name,
            newsCount,
            policiesCount,
          });
        } catch (err) {
          result.errors.push(`Error processing ${candidate.name}: ${err}`);
        }

        // Small delay between candidates
        await new Promise(resolve => setTimeout(resolve, 2000));
      }

      // Delay between batches
      if (i + BATCH_SIZE < candidates.length) {
        console.log(`[Scheduler] Processed batch ${Math.floor(i / BATCH_SIZE) + 1}, waiting...`);
        await new Promise(resolve => setTimeout(resolve, BATCH_DELAY));
      }
    }
  } catch (err) {
    result.errors.push(`Scheduler error: ${err}`);
  }

  isRunning = false;
  lastRunTime = startTime;
  lastRunResult = result;

  const endTime = new Date();
  const duration = (endTime.getTime() - startTime.getTime()) / 1000;
  console.log(`[Scheduler] Update completed in ${duration}s`);
  console.log(`[Scheduler] Results: ${result.candidatesProcessed} candidates, ${result.newsAdded} news, ${result.policiesAdded} policies`);

  return result;
}

/**
 * Start the scheduler
 */
export function startScheduler(): void {
  if (schedulerInterval) {
    console.log("[Scheduler] Scheduler already running");
    return;
  }

  console.log("[Scheduler] Starting scheduler (interval: 6 hours)");
  
  // Run immediately on start (with a small delay to let server initialize)
  setTimeout(() => {
    console.log("[Scheduler] Running initial update...");
    runScheduledUpdate().catch(err => {
      console.error("[Scheduler] Initial update failed:", err);
    });
  }, 30000); // 30 second delay after server start

  // Schedule recurring updates
  schedulerInterval = setInterval(() => {
    console.log("[Scheduler] Running scheduled update...");
    runScheduledUpdate().catch(err => {
      console.error("[Scheduler] Scheduled update failed:", err);
    });
  }, UPDATE_INTERVAL);
}

/**
 * Stop the scheduler
 */
export function stopScheduler(): void {
  if (schedulerInterval) {
    clearInterval(schedulerInterval);
    schedulerInterval = null;
    console.log("[Scheduler] Scheduler stopped");
  }
}

/**
 * Get scheduler status
 */
export function getSchedulerStatus(): {
  isRunning: boolean;
  lastRunTime: Date | null;
  lastRunResult: SchedulerResult | null;
  nextRunTime: Date | null;
} {
  return {
    isRunning,
    lastRunTime,
    lastRunResult,
    nextRunTime: lastRunTime 
      ? new Date(lastRunTime.getTime() + UPDATE_INTERVAL)
      : null,
  };
}

/**
 * Manually trigger an update for a specific candidate
 */
export async function triggerCandidateUpdate(candidateId: number): Promise<{
  success: boolean;
  newsCount: number;
  policiesCount: number;
  errors: string[];
}> {
  const candidate = await db.getCandidateById(candidateId);
  if (!candidate) {
    return {
      success: false,
      newsCount: 0,
      policiesCount: 0,
      errors: ["Candidate not found"],
    };
  }

  console.log(`[Scheduler] Manual update triggered for ${candidate.name}`);
  const result = await processCandidate({
    id: candidate.id,
    name: candidate.name,
    county: candidate.county,
    party: candidate.party,
    positionType: candidate.positionType,
  });

  return {
    success: result.errors.length === 0,
    ...result,
  };
}
